Repository mobile-dev-inc/maestro, pull requests merged in 2024-05, with the labels that each got.

#1671 Fix "Protocol family unavailable" on rerun after failure
  maestro-ios-driver/src/main/kotlin/xcuitest/installer/LocalXCTestInstaller.kt
Labels: bug, ios, external-contribution

#1749 Add jenv config file
  .java-version
Labels: enhancement, external-contribution

#1750 add new test report format: HTML
  maestro-cli/build.gradle.kts
  maestro-cli/src/main/java/maestro/cli/report/HtmlTestSuiteReporter.kt
  maestro-cli/src/main/java/maestro/cli/report/ReportFormat.kt
  maestro-cli/src/main/java/maestro/cli/report/ReporterFactory.kt
Labels: enhancement, external-contribution

#1672 feat: allow airplane mode control
  maestro-client/src/main/java/maestro/Driver.kt
  maestro-client/src/main/java/maestro/Errors.kt
  maestro-client/src/main/java/maestro/Maestro.kt
  maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
  maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
  maestro-client/src/main/java/maestro/drivers/WebDriver.kt
  maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
  maestro-orchestra-models/src/main/java/maestro/orchestra/MaestroCommand.kt
  maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
  maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
  maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlSetAirplaneMode.kt
  maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlToggleAirplaneMode.kt
  maestro-test/src/main/kotlin/maestro/test/drivers/FakeDriver.kt
  maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
  maestro-test/src/test/resources/115_airplane_mode.yaml
Labels: enhancement, android, external-contribution

#1720 Update Ktor and logback to mitigate security risks
  gradle.properties
  gradle/libs.versions.toml
Labels: external-contribution
